### ISSUE TITLE
What is the purpose of NewsletterSignupUser?

### ISSUE THREAD

**Issue by mkoistinen** [aldryn/aldryn-jobs#75]
Current, the NewsletterSignup and django.contrib.auth.User models are "connected" via what appears to be a M2M through table as shown here:

![image](https://cloud.githubusercontent.com/assets/615759/8636595/e1111dee-2838-11e5-9031-772855f37754.png)

In reviewing the codebase and, in particular, the tests. It is unclear how more than a single User would ever need to be attached to the same NewsletterSignup object (which contains only a single field, recipient, for holding a single email address.)

If it is true that its a zero or one relationship, then the NewsletterSignupUser model should be removed, and a single FK should be added on NewsletterSignup that references User.

Am I missing something?

@cyberstar your thoughts please.

**Comment by cyberstar** [comment]
@mkoistinen the idea behind newsletter signup was to make a weak tie between newsletter signup and a user, since user is not required for signing up for jobs newsletter. User is only used to make appropriate greeting (if there is user - use user's full_name instead of general greeting).
That was a trial to allow a single user to have multiple signups, but i think that maybe it was a poor design decision and can be easily replaced to strong reference to User with blank=True.

**Comment by mkoistinen** [comment]
To be closed by #83

**Comment by mkoistinen** [comment]
Closed by #83
